--- #YAML:1.0
name:               Cache-FastMmap-WithWin32
version:            1.28.1
abstract:           Uses an mmap'ed file to act as a shared memory interprocess cache
author:
    - Rob Mueller <cpan@robm.fastmail.fm>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Storable:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
