--- #YAML:1.0
name:                Cache-FastMmap-WithWin32
version:             1.16.3
abstract:            Uses an mmap'ed file to act as a shared memory interprocess cache
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Storable:                      0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Ash Berlin <cpan@cpan.org>
